### ISSUE TITLE
https://hackclub.com/hackathons/ 404 Error

### ISSUE THREAD

**Issue by gleich** [hackclub/v2#546]
Under the page clubs section, there is a tile that says "Attend hackathons, workshops, & other local events from Hack Clubs near yours. See near by events" When you click on "See near by events, you get a 404 page not found error.

**Comment by zachlatta** [comment]
Wow, thanks! I’m on it, will push a fix shortly.

**Comment by zachlatta** [comment]
@lachlanjc: assigning to you, I'm getting some JS errors when trying to launch the dev environment.

It looks like https://github.com/hackclub/site/blob/master/src/pages/start.js#L468 is the suspect line.

We do have a Netlify redirect in place to redirect `/hackathons` to https://hackathons.hackclub.com, but `FeatureLink` causes Gatsby to do local routing instead of actually querying `/hackathons` from the underlying web server.

Best solution is to just link directly to https://hackathons.hackclub.com from that component, as it's the only time we're ever referencing `/hackathons` as far as I can tell.
