### ISSUE TITLE
Allow clubs to claim subdomains on hackclub.com

### ISSUE THREAD

**Issue by ifvictr** [hackclub/v2#77]
From https://hackclub.slack.com/archives/C0C78SG9L/p1513628267000382.

This will require use of the DNSimple API.

**Comment by lachlanjc** [comment]
The main part of this will be implemented on hackclub/monolith, but we’ll probably need a form (/login system? yikes) to mange the individual records

**Comment by itsmingjie** [comment]
@lachlanjc ^^ That would basically require a fully functional dashboard authentication system... And if that's ever possible we should probably make check-in available there too... along with the millions of other things that we've wanted to do (picture collection... Communicating...)

And I don't think that at this moment is possible... Due to the tremendous amount of work that this may require...

**Comment by ifvictr** [comment]
@mj66 A project like this most likely won't be on the main website. It'll be at `https://dashboard.hackclub.com`.

**Comment by ifvictr** [comment]
Nevertheless, the centralized dashboard sounds like a good idea.

**Comment by zanedb** [comment]
So maybe move this issue to part of todo list for a unified dashboard?

**Comment by ifvictr** [comment]
@zanedb I'm planning to help make this after I finish some other projects. Feel free to make it if you can! :)

**Comment by lachlanjc** [comment]
I’m going to close this for now as it’s not a project we’re taking on right now. But I’m sure the community would love it, and we totally should do this at some point!
